const size = [
  { value: 1, selected: false },
  { value: 2, selected: false },
  { value: 3, selected: false },
  { value: 4, selected: false },
  { value: 5, selected: false },
  { value: 6, selected: false },
  { value: 7, selected: false },
  { value: 9, selected: false },
  { value: 10, selected: false },
  { value: 11, selected: false },
  { value: 12, selected: false },
  { value: 13, selected: false },
  { value: 14, selected: false },
  { value: 15, selected: false },
  { value: 16, selected: false },
  { value: 17, selected: false },
  { value: 18, selected: false },
  { value: 19, selected: false },
  { value: 20, selected: false },
  { value: 21, selected: false },
  { value: 22, selected: false },
  { value: 23, selected: false },
  { value: 24, selected: false },
  { value: 25, selected: false },
];

export default size;
